/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import conexion.ConnectionTableDB;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.xml.sax.SAXException;

/**
 *
 * @author Advantech Digital
 */
public class AsignarCliente extends javax.swing.JFrame {

    /**
     * Creates new form AsignarCliente
     */
    public AsignarCliente(String usuario, String contraseña) {
        USER = usuario;
        PASSWORD = contraseña;
        String consulta = "SELECT * FROM cliente LIMIT 50";
        try {
            model = new ConnectionTableDB(USER, PASSWORD, DB, consulta, true);
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        File consumidor = new File(XML_PATH);
        File cliente = new File(ASIGNADOS);
        if (!consumidor.exists())
            consumidor.mkdir();
        if (!cliente.exists())
            cliente.mkdir();
        xml = new File(XML_PATH).listFiles();
        modeloTabla = new ModeloTablaXML(xml);
        initComponents();
        if (tablaXML.getRowCount() == 0){
            txtAXML.setText("No existen más facturas a Consumidor Final.");
            btnBuscarCliente.setEnabled(false);
        }
        Clientes.setUndecorated(true);
        Clientes.setSize(1000, 560);
        sorter = new TableRowSorter<TableModel>(model);
        sorter.setRowFilter(null);
        tablaClientes.setRowSorter(sorter);
           this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    
    }
    
    private void createTable(){
        xml = new File(XML_PATH).listFiles();
        modeloTabla.update(xml);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clientes = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtBuscado = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaXML = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAXML = new javax.swing.JTextArea();

        Clientes.setExtendedState(2);
        Clientes.setName("frameClientes"); // NOI18N
        Clientes.setResizable(false);

        jLabel3.setText("Buscar:");
        jPanel2.add(jLabel3);

        txtBuscar.setColumns(30);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        jPanel2.add(txtBuscar);

        Clientes.getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tablaClientes.setModel(model);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaClientesMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaClientes);

        Clientes.getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        txtBuscado.setEditable(false);
        txtBuscado.setColumns(30);
        jPanel3.add(txtBuscado);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel3.add(btnOK);

        Clientes.getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        Clientes.getAccessibleContext().setAccessibleParent(this);

        setTitle("Asignar Cliente");
        setName("interfaz"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnAsignar.setText("Asignar Cliente");
        btnAsignar.setEnabled(false);
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Cliente:");

        txtId.setEditable(false);

        txtCliente.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(txtId)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 400));

        tablaXML.setModel(modeloTabla);
        tablaXML.setShowVerticalLines(false);
        tablaXML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaXMLMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaXML);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerifyInputWhenFocusTarget(false);

        txtAXML.setEditable(false);
        txtAXML.setColumns(10);
        txtAXML.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtAXML.setRows(5);
        txtAXML.setTabSize(4);
        jScrollPane2.setViewportView(txtAXML);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        btnBuscarCliente.setEnabled(false);
        Clientes.setVisible(true);
        Clientes.requestFocus();
        setEnabled(false);
        try {
            model.consulta("SELECT cedula_ruc ID, nombre Cliente, tipo_identificacion Tipo, Direccion, Telefono, Codigo FROM cliente");
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (model.connected)
            model.desconectar();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        setEnabled(true);
        txtId.requestFocus();
        Clientes.setVisible(false);
        if (tablaXML.getRowCount() != 0 && rowXML >= 0)
            btnAsignar.setEnabled(true);
        btnBuscarCliente.setEnabled(true);
        if (!(rowClientes < 0)){
        txtId.setText((String)tablaClientes.getValueAt(rowClientes, 0));
        txtCliente.setText((String)tablaClientes.getValueAt(rowClientes, 1));
        if (tablaClientes.getValueAt(rowClientes, 2) != null)
        switch ((String)tablaClientes.getValueAt(rowClientes, 2)){
            case "cedula" :
                tipo = "05";
                break;
            case "ruc" :
                tipo = "04";
                break;
            case "pasaporte" :
                tipo = "06";
                break;
            case "placa" :
                tipo = "09";
                break;
            default :
                tipo = null;
                break;
        }}
    }//GEN-LAST:event_btnOKActionPerformed

    private void tablaClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMousePressed
        // TODO add your handling code here:
        rowClientes = tablaClientes.rowAtPoint(evt.getPoint());
        txtBuscado.setText(String.format("Seleccionado: %s", (String)tablaClientes.getValueAt(rowClientes, 1)));
    }//GEN-LAST:event_tablaClientesMousePressed

    private void tablaXMLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaXMLMousePressed
        // TODO add your handling code here:
        rowXML = tablaXML.rowAtPoint(evt.getPoint());
        if (!(rowXML < 0)) {
        try {
            btnAsignar.setEnabled(true);
            DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            doc = builder.parse(xml[rowXML]);
            Element root = doc.getDocumentElement();
            root.normalize();
            Node infoTributaria = root.getElementsByTagName("infoTributaria").item(0);
            String emisor = ((Element)infoTributaria).getElementsByTagName("razonSocial").item(0).getFirstChild().getNodeValue();
            String comercial = ((Element)infoTributaria).getElementsByTagName("nombreComercial").item(0).getFirstChild().getNodeValue();
            String ruc = ((Element)infoTributaria).getElementsByTagName("ruc").item(0).getFirstChild().getNodeValue();
            
            Node detalle = ((Element)root.getElementsByTagName("detalles").item(0)).getElementsByTagName("detalle").item(0);
            String producto = ((Element)detalle).getElementsByTagName("descripcion").item(0).getFirstChild().getNodeValue();
            String cantidad = ((Element)detalle).getElementsByTagName("cantidad").item(0).getFirstChild().getNodeValue();
            
            Node infoFactura = root.getElementsByTagName("infoFactura").item(0);
            String fecha = ((Element)infoFactura).getElementsByTagName("fechaEmision").item(0).getFirstChild().getNodeValue();
            String nombre = ((Element)infoFactura).getElementsByTagName(NOMBRE).item(0).getFirstChild().getNodeValue();
            String id = ((Element)infoFactura).getElementsByTagName(ID).item(0).getFirstChild().getNodeValue();
            String total = ((Element)infoFactura).getElementsByTagName("importeTotal").item(0).getFirstChild().getNodeValue();
            
            nodos = new Node[infoFactura.getChildNodes().getLength()];
            for (int i = 0; i < nodos.length; i++){
                nodos[i] = infoFactura.getChildNodes().item(i);
            }
            
            txtAXML.setText(String.format("Factura Seleccionada: %s\n"
                                        + "Fecha:                %s\n\n"
                                        + "EMISOR:\n"
                                        + "%-15s%20s\n"
                                        + "%-15s%20s\n"
                                        + "%-15s%20s\n\n"
                                        + "CLIENTE:\n"
                                        + "%-15s%20s\n"
                                        + "%-15s%20s\n\n"
                                        + "DETALLE:\n"
                                        + "%-15s%20s\n"
                                        + "%-15s%20s galones.\n"
                                        + "%-15s%20s\n",
                                        (String)tablaXML.getValueAt(rowXML, 0),
                                        fecha,
                                        "Nombre: ", emisor,
                                        "Comercial: ", comercial,
                                        "Id. Emisor: ", ruc,
                                        "Nombre: ", nombre,
                                        "Id: ", id,
                                        "Producto: ", producto,
                                        "Cantidad: ", cantidad,
                                        "Total Factura: ", "$ " + total));
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            System.out.println(ex.getMessage());
        }}
    }//GEN-LAST:event_tablaXMLMousePressed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        if (txtCliente.getText().length() == 0)
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        else{
        try {
            // TODO add your handling code here:
            for (int i = 0; i < nodos.length; i ++){
                if (TIPO.equals(nodos[i].getNodeName()))
                    nodos[i].setTextContent(tipo);
                if (NOMBRE.equals(nodos[i].getNodeName()))
                    nodos[i].setTextContent(txtCliente.getText());
                if (ID.equals(nodos[i].getNodeName()))
                    nodos[i].setTextContent(txtId.getText());
            }
            Transformer transformer = TransformerFactory.newInstance().newTransformer();
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(ASIGNADOS + "\\" + xml[rowXML].getName());
            transformer.transform(source, result);
            xml[rowXML].delete();
            createTable();
            if (tablaXML.getRowCount() == 0){
                btnAsignar.setEnabled(false);
                txtAXML.setText("No existen más facturas a Consumidor Final.");
            }
            JOptionPane.showMessageDialog(this, "Cliente asignado correctamente.");
        } catch (TransformerConfigurationException ex) {
            System.out.println(ex.getMessage());
        } catch (TransformerException ex) {
            System.out.println(ex.getMessage());
        }}
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        try {
            model.consulta("SELECT cedula_ruc ID, nombre Cliente, tipo_identificacion Tipo, Direccion, Telefono, Codigo "
                        + "FROM cliente WHERE cedula_ruc LIKE '" + txtBuscar.getText() + "%' LIMIT 50");
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        String filtro = txtBuscar.getText();
        if (filtro.length() == 0){
            sorter.setRowFilter(null);
        }
        else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro));
            } catch (PatternSyntaxException ex) {
                System.out.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new AsignarCliente(USER, PASSWORD).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Clientes;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaXML;
    private javax.swing.JTextArea txtAXML;
    private javax.swing.JTextField txtBuscado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
    private ConnectionTableDB model;
    private String USER = "";
    private String PASSWORD = "";
    private final String DB = "adv_facturacion";
    private final String XML_PATH = "consumidores_finales";
    private final String ASIGNADOS = "clientes_asignados";
    private final String TIPO = "tipoIdentificacionComprador";
    private final String NOMBRE = "razonSocialComprador";
    private final String ID = "identificacionComprador";
    private String tipo;
    private int rowClientes = -1;
    private int rowXML = -1;
    private File[] xml;
    private Document doc;
    private Node[] nodos;
    private ModeloTablaXML modeloTabla;
    private TableRowSorter<TableModel> sorter;
}
