/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author r
 */
import conexion.conexion_facturacion;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class estados_cuenta extends javax.swing.JFrame {

    public DefaultListModel modelo = new DefaultListModel();
    MiModelo litabla = new MiModelo();
    conexion_facturacion n;

    /**
     * Creates new form estados_cuenta
     */
    public estados_cuenta(String usuario, String contraseña) {
        try {
            this.usu = usuario;
            this.contra = contraseña;

            n = new conexion_facturacion(usu, contra);
            n.conectar();
            initComponents();
            this.setExtendedState(this.MAXIMIZED_BOTH);

            litabla.addColumn("Nº");
            litabla.addColumn("Nombre");
            litabla.addColumn("Cedula/ruc");
            litabla.addColumn("Correo");
            litabla.addColumn("Credito");
            litabla.addColumn("Cupo");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public class MiModelo extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {

            return false;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fechai = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        fechaf = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        rcliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 1060, 313);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2, 0, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Fecha Inicial");
        jPanel2.add(jLabel2);
        jPanel2.add(fechai);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Fecha Final");
        jPanel2.add(jLabel1);
        jPanel2.add(fechaf);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cliente Ruc");
        jPanel2.add(jLabel3);

        rcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rclienteKeyTyped(evt);
            }
        });
        jPanel2.add(rcliente);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cliente Razon Social");
        jPanel2.add(jLabel4);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("E-mail");
        jPanel2.add(jLabel6);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 30, 520, 200);

        jButton1.setText("Visualizar Estado de Cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 30, 220, 23);

        jButton2.setText("Enviar al E-mail del cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 80, 220, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cliente Razon Social");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 182, 22);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String ruc;

    public void LimpiarJTable() {

        litabla.setNumRows(0);


    }
    Object datos[] = new Object[7];
    private void rclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rclienteKeyTyped

        char c = evt.getKeyChar();


        if (c < '0' || c > '9') {
            getToolkit().beep();

            evt.consume();



        }




        ruc = rcliente.getText();
        try {

            n.conectar();

            LimpiarJTable();
            int id = 0, telefono = 0;
            String nombrec = null, mail = null, cedula;



            Statement st_im1 = n.coneccion.createStatement();
            ResultSet ridim1 = st_im1.executeQuery("SELECT idcliente,nombre,cedula_ruc,email,credito_cliente,cupo_cliente FROM adv_facturacion.cliente  WHERE credito_cliente=1 and (cedula_ruc) like ( '" + ruc + "%' )  group by nombre limit 100");


            System.out.println("SELECT idcliente,nombre,cedula_ruc,email,codigo,credito_cliente,cupo_cliente FROM adv_facturacion.cliente  WHERE  (cedula_ruc) like ( '" + ruc + "%' ) limit 100");




            while (ridim1.next()) {



                for (int i = 0; i < 6; i++) {
                    datos[i] = ridim1.getObject(i + 1);

                    //datos[i] = consultac.getObject(i + 1);
                }
                litabla.addRow(datos);
            }
            tabla.setModel(litabla);


            st_im1.close();
            ridim1.close();

            n.coneccion.close();
        } catch (SQLException ex) {
        } catch (java.lang.NullPointerException ex) {

            System.out.println("cliente no encontrado");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    String contra, usu;

    public void usuarios(String usuario, String contraseña) {
        try {
            contra = contraseña;
            usu = usuario;
            n = new conexion_facturacion(usu, contra);
            n.conectar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    private void cclienteKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();


        if (c < '0' || c > '9') {
            getToolkit().beep();

            evt.consume();



        }




    }//GEN-LAST:event_rclienteKeyTyped

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed
    String correo = "", idc = "";
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        String cedula = "";
        String nombrec = "";
        String direccion = "";

        try {

            DefaultTableModel tm = (DefaultTableModel) tabla.getModel();
            cedula = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 2));
            nombrec = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 1));
            direccion = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 4));
            correo = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 3));

            if (correo == null) {

                correo = "";

            }
            idc = String.valueOf(tm.getValueAt(tabla.getSelectedRow(), 0));


            nombre.setText(nombrec);
            rcliente.setText(cedula);
            email.setText(correo);








        } catch (java.lang.NumberFormatException ex) {
        }
    }//GEN-LAST:event_tablaMouseClicked
    String ff, fi;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int añoi = fechai.getCalendar().get(Calendar.YEAR);
            int mesi = fechai.getCalendar().get(Calendar.MONTH) + 1;
            int diai = fechai.getCalendar().get(Calendar.DAY_OF_MONTH);


            fi = añoi + "-" + mesi + "-" + diai;


            int añof = fechaf.getCalendar().get(Calendar.YEAR);
            int mesf = fechaf.getCalendar().get(Calendar.MONTH) + 1;
            int diaf = fechaf.getCalendar().get(Calendar.DAY_OF_MONTH);


            ff = añof + "-" + mesf + "-" + diaf;
            System.out.println(fi);
            System.out.println(ff);
            System.out.println(idc);

            n.conectar();

            Map parameters = new HashMap();
            parameters.put("fechai", fi);
            parameters.put("fechaf", ff);
            parameters.put("cliente", idc);


            JasperReport report = JasperCompileManager.compileReport("estado_cuenta.jrxml");
            JasperPrint print = JasperFillManager.fillReport(report, parameters, n.coneccion);
            // Exporta el informe a PDF
            //JasperExportManager.exportReportToPdfFile(print, "venta_combu.pdf");
            //Para visualizar el pdf directamente desde java
            JasperViewer.viewReport(print, false);



        } catch (ClassNotFoundException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            int añoi = fechai.getCalendar().get(Calendar.YEAR);
            int mesi = fechai.getCalendar().get(Calendar.MONTH) + 1;
            int diai = fechai.getCalendar().get(Calendar.DAY_OF_MONTH);


            fi = añoi + "-" + mesi + "-" + diai;


            int añof = fechaf.getCalendar().get(Calendar.YEAR);
            int mesf = fechaf.getCalendar().get(Calendar.MONTH) + 1;
            int diaf = fechaf.getCalendar().get(Calendar.DAY_OF_MONTH);


            ff = añof + "-" + mesf + "-" + diaf;
            System.out.println(fi);
            System.out.println(ff);
            System.out.println(idc);

            n.conectar();

            Map parameters = new HashMap();
           
            parameters.put("fechai", fi);
            parameters.put("fechaf", ff);
            parameters.put("cliente", idc);


            JasperReport report = JasperCompileManager.compileReport("estado_cuenta.jrxml");
            JasperPrint print = JasperFillManager.fillReport(report, parameters, n.coneccion);
            // Exporta el informe a PDF
            JasperExportManager.exportReportToPdfFile(print, "estado_cuenta.pdf");



            //Para visualizar el pdf directamente desde java
            // JasperViewer.viewReport(print, false);



        } catch (ClassNotFoundException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(estados_cuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estados_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estados_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estados_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estados_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estados_cuenta("root", "manager").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private com.toedter.calendar.JDateChooser fechaf;
    private com.toedter.calendar.JDateChooser fechai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField rcliente;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
